### ISSUE TITLE
Unable to import roerich due to potential version mismatch

### ISSUE THREAD

**Issue by rahulsinghalmrt** [HSE-LAMBDA/roerich#1]
Hi,

Thanks for sharing the code. I was trying to follow the instructions for basic usage  but got following error:
```
import roerich
Traceback (most recent call last):
  File "C:\Users\arago\.p2\pool\plugins\org.python.pydev.core_8.1.0.202012051215\pysrc\_pydevd_bundle\pydevd_exec2.py", line 3, in Exec
    exec(exp, global_vars, local_vars)
  File "<console>", line 1, in <module>
  File "C:\Users\arago\AppData\Local\Programs\Python\Python39\lib\site-packages\roerich\__init__.py", line 1, in <module>
    from .algorithms import OnlineNNClassifier, OnlineNNRuLSIF
  File "C:\Users\arago\AppData\Local\Programs\Python\Python39\lib\site-packages\roerich\algorithms.py", line 7, in <module>
    import torch
  File "C:\Users\arago\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\__init__.py", line 196, in <module>
    from torch._C import *
RuntimeError: module compiled against API version 0xe but this version of numpy is 0xd
```
Thanks,
Rahul

**Comment by hushchyn-mikhail** [comment]
Hi @rahulsinghalmrt,

Thank you very much for using our code. Could you provide the versions of numpy and pytorch you were using please?
We are also updating our library. `roerich==0.3.0` contains a list of dependencies in `setup.py`. We hope it will be useful.

Thanks,
Mikhail
